### ISSUE TITLE
Define Lints

### ISSUE THREAD

**Issue by bienvenuelisis** [iuxcode/Messenger_X#3]
Because this projet is collaborative and collaborations are widely accepted from all contributors that want to help, i think a good way to enforce consistents rules are with lints.

So i'm suggesting :
 - [Austerity](https://pub.dev/packages/austerity) as foundation ;
 - And custom lints according to mainteners desires 
 - If necessary use [custom_lint](https://pub.dev/packages/custom_lint)

**Comment by iuxcode** [comment]
Closed since this problem has been solved. Check this [commit](https://github.com/iuxcode/Messenger_X/commit/90d9a58260065223e8b3eb6cf52c884f3857fa09)
